{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "go.fullname" . }}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ $val | quote}}
  {{- end }}
{{- end }}
