{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "go.fullname" . }}
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val|b64enc | quote}}
  {{- end }}
{{- end }}
---
{{- if .Values.secretAsFile }}
{{- range $key, $val := .Values.secretAsFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "go.fullname" $ }}-{{ $key | replace "." "-" }}
data:
  {{ $key }}: {{ $val.content|b64enc | quote }}
{{- end }}
{{- end }}