---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-ssh-credentials
  url: ssh://git@github.com/luca-iachini/fluxcd-test

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/dev/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev

