---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./chart/go
      sourceRef:
        kind: GitRepository
        name: dev
  interval: 30s
  targetNamespace: dev
  values:
    image:
      pullPolicy: IfNotPresent
      registry: registry.localhost:5000
      repository: fluxcd-test/app1
      tag: 0.0.1
    resources:
      limits:
        cpu: 100m
        memory: 120Mi
      requests:
        cpu: 100m
        memory: 120Mi

