---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app1
  namespace: flux-system
spec:
  image: registry.localhost:5000/fluxcd-test/app1
  interval: 1m0s
  secretRef:
    name: regcred

