---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dev-app1
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app1
  policy:
    semver:
      range: 0.0.x

